version: '3'
services:

  db:
    image:
      mysql:5.7
    environment:
      MYSQL_DATABASE: 'ebaysniper'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

volumes:
  db_data:
